"""Remove timezone column from users table

Revision ID: 70a702f5707c
Revises: a5cfbf9cdf76
Create Date: 2024-11-02 14:12:27.950396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a702f5707c'
down_revision = 'a5cfbf9cdf76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
