"""New migration

Revision ID: a5cfbf9cdf76
Revises: 01807e96a26d
Create Date: 2024-10-29 17:28:33.512581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5cfbf9cdf76'
down_revision = '01807e96a26d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
