"""Make timestamps timezone-aware

Revision ID: c47c13f6b798
Revises: 70a702f5707c
Create Date: 2024-11-02 14:31:16.400891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47c13f6b798'
down_revision = '70a702f5707c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
